# Generated by Django 4.2.16 on 2024-11-23 03:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tiendita.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('RutUsuario', models.IntegerField(unique=True)),
                ('NombreUsuario', models.CharField(blank=True, max_length=80, null=True)),
                ('ApellidoUsuario', models.CharField(blank=True, max_length=80, null=True)),
                ('EmailUsuario', models.EmailField(max_length=128)),
                ('TelefonoUsuario', models.CharField(blank=True, help_text='Formato: +56 9 12345678', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número debe tener formato +56 seguido de 9 dígitos', regex='^\\+56[0-9]{9}$')])),
                ('DomicilioUsuario', models.CharField(blank=True, max_length=200, null=True)),
                ('TipoAnimal', models.FloatField(blank=True, choices=[(0.1, 'Gato'), (0.2, 'Perro'), (0.3, 'Ave'), (0.4, 'Hamster')], null=True)),
                ('ImagenPerfil', models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[tiendita.models.validate_image_file_extension])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_veterinario', models.BooleanField(default=False)),
                ('is_comerciante', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCliente', models.CharField(blank=True, max_length=200, null=True)),
                ('ApellidoCliente', models.CharField(blank=True, max_length=200, null=True)),
                ('EmailCliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('TelefonoCliente', models.CharField(blank=True, max_length=20, null=True)),
                ('DireccionCliente', models.TextField(blank=True, null=True)),
                ('FechaOrden', models.DateTimeField(auto_now_add=True)),
                ('EstadoOrden', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('TotalOrden', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CostoEnvio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TokenWebpay', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCompletoVeterinario', models.CharField(help_text='Ingrese su nombre completo incluyendo títulos (ej: Dr. Juan Pérez González)', max_length=200, verbose_name='Nombre Completo')),
                ('EmailVeterinario', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('TelefonoVeterinario', models.BigIntegerField(help_text='Ingrese los 9 dígitos de su número celular', validators=[django.core.validators.MinValueValidator(900000000, message='El número debe tener 9 dígitos'), django.core.validators.MaxValueValidator(999999999, message='El número debe tener 9 dígitos')], verbose_name='Teléfono')),
                ('Especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('NumeroRegistro', models.CharField(max_length=50, unique=True, verbose_name='Número de Registro')),
                ('Descripcion', models.TextField(help_text='Describa su experiencia y servicios principales', verbose_name='Descripción Profesional')),
                ('ImagenPerfil', models.ImageField(blank=True, null=True, upload_to='perfiles_veterinarios/', validators=[tiendita.models.validate_image_file_extension], verbose_name='Foto de Perfil')),
                ('Ubicacion', models.CharField(blank=True, help_text='Dirección donde atiende (puede ser editada posteriormente)', max_length=200, verbose_name='Dirección')),
                ('MostrarUbicacion', models.BooleanField(default=True, verbose_name='Mostrar ubicación públicamente')),
                ('Latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Se autocompletará al ingresar la dirección', max_digits=9, null=True)),
                ('Longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Se autocompletará al ingresar la dirección', max_digits=9, null=True)),
                ('EstaActivo', models.BooleanField(default=True, verbose_name='Perfil Activo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_veterinario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Veterinario',
                'verbose_name_plural': 'Perfiles de Veterinarios',
                'ordering': ['NombreCompletoVeterinario'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKUProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=128)),
                ('StockProducto', models.IntegerField()),
                ('PrecioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecioOferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('EstaOferta', models.BooleanField(default=False)),
                ('DescripcionProducto', models.CharField(max_length=500)),
                ('CategoriaProducto', models.FloatField(choices=[(0.1, 'Alimentos'), (0.2, 'Accesorios'), (0.3, 'Juguetes'), (0.4, 'Camas y rascadores')])),
                ('TipoAnimal', models.FloatField(choices=[(0.1, 'Gato'), (0.2, 'Perro'), (0.3, 'Ave'), (0.4, 'Hamster')])),
                ('ImagenProducto', models.ImageField(blank=True, null=True, upload_to='productos/', validators=[tiendita.models.validate_image_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='ServicioBase',
            fields=[
                ('CodigoServicio', models.AutoField(primary_key=True, serialize=False)),
                ('NombreServicio', models.CharField(max_length=100)),
                ('TipoServicio', models.CharField(choices=[('CONSULTA', 'Consulta General'), ('VACUNA', 'Vacunación'), ('CIRUGIA', 'Cirugía'), ('EMERGENCIA', 'Emergencia'), ('GROOMING', 'Peluquería'), ('DENTAL', 'Limpieza Dental'), ('ESPECIALIDAD', 'Consulta Especialidad')], max_length=50)),
                ('EstaActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio Base',
                'verbose_name_plural': 'Servicios Base',
                'db_table': 'ServicioBase',
                'ordering': ['TipoServicio', 'NombreServicio'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('PrecioProducto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CantidadProducto', models.IntegerField(blank=True, null=True)),
                ('SKUProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendita.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tiendita.orden')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('HorarioInicio', models.TimeField()),
                ('HorarioFin', models.TimeField()),
                ('EstaDisponible', models.BooleanField(default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('UltimaActualizacion', models.DateTimeField(auto_now=True)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='tiendita.perfilveterinario')),
            ],
            options={
                'ordering': ['Fecha', 'HorarioInicio'],
            },
        ),
        migrations.CreateModel(
            name='ServicioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, help_text='Precio del servicio', max_digits=10)),
                ('EstaActivo', models.BooleanField(default=True)),
                ('Notas', models.TextField(blank=True, null=True)),
                ('servicio_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='tiendita.serviciobase')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_personalizados', to='tiendita.perfilveterinario')),
            ],
            options={
                'verbose_name': 'Servicio Personalizado',
                'verbose_name_plural': 'Servicios Personalizados',
                'unique_together': {('veterinario', 'servicio_base')},
            },
        ),
        migrations.CreateModel(
            name='ResenaVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Comentario', models.TextField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_veterinarios', to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='tiendita.perfilveterinario')),
            ],
            options={
                'verbose_name': 'Reseña de Veterinario',
                'verbose_name_plural': 'Reseñas de Veterinarios',
                'ordering': ['-FechaCreacion'],
                'unique_together': {('veterinario', 'usuario')},
            },
        ),
        migrations.AddConstraint(
            model_name='disponibilidadveterinario',
            constraint=models.UniqueConstraint(fields=('veterinario', 'Fecha', 'HorarioInicio'), name='unique_veterinario_fecha_inicio'),
        ),
    ]
