# Generated by Django 4.2.16 on 2024-11-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKUProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=128)),
                ('StockProducto', models.IntegerField()),
                ('PrecioProducto', models.FloatField()),
                ('PrecioOferta', models.FloatField()),
                ('EstaOferta', models.BooleanField(default=False)),
                ('DescripcionProducto', models.CharField(max_length=500)),
                ('CategoriaProducto', models.FloatField(choices=[(0.1, 'Alimentos'), (0.2, 'Accesorios'), (0.3, 'Juguetes'), (0.4, 'Camas y rascadores')])),
                ('TipoAnimal', models.FloatField(choices=[(0.1, 'Gato'), (0.2, 'Perro'), (0.3, 'Ave'), (0.4, 'Hamster')])),
                ('ImagenProducto', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('CodigoVeterinaria', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreVeterinaria', models.CharField(max_length=100)),
                ('LocalidadVeterinaria', models.CharField(max_length=100)),
                ('HorarioInicioVeterinaria', models.DateTimeField()),
                ('HorarioCierreVeterinaria', models.DateTimeField()),
                ('CalificacionVeterinaria', models.FloatField()),
                ('DisponibilidadVeterinaria', models.CharField(max_length=1)),
                ('TipoAnimal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('CodigoUnicoOrden', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=128)),
                ('RutUsuario', models.IntegerField()),
                ('EmailUsuario', models.CharField(max_length=128)),
                ('DomicilioUsuario', models.CharField(max_length=128)),
                ('FechaEstimadaOrden', models.DateField()),
                ('SKUProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('RutUsuario', models.IntegerField(unique=True)),
                ('NombreUsuario', models.CharField(blank=True, max_length=80, null=True)),
                ('EmailUsuario', models.EmailField(max_length=128)),
                ('DomicilioUsuario', models.CharField(blank=True, max_length=200, null=True)),
                ('TipoAnimal', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
