# Generated by Django 4.2.16 on 2024-10-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKUProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=128)),
                ('StockProducto', models.IntegerField()),
                ('PrecioProducto', models.FloatField()),
                ('DescripcionProducto', models.CharField(max_length=500)),
                ('TipoAnimal', models.FloatField()),
                ('ImagenProducto', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('RutUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=80)),
                ('PasswordUsuario', models.CharField(max_length=20)),
                ('EmailUsuario', models.CharField(max_length=128)),
                ('DomicilioUsuario', models.CharField(max_length=128)),
                ('TipoAnimal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('CodigoVeterinaria', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreVeterinaria', models.CharField(max_length=100)),
                ('LocalidadVeterinaria', models.CharField(max_length=100)),
                ('HorarioInicioVeterinaria', models.DateTimeField()),
                ('HorarioCierreVeterinaria', models.DateTimeField()),
                ('CalificacionVeterinaria', models.FloatField()),
                ('DisponibilidadVeterinaria', models.CharField(max_length=1)),
                ('TipoAnimal', models.FloatField()),
                ('RutUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('CodigoUnicoOrden', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=128)),
                ('RutUsuario', models.IntegerField()),
                ('EmailUsuario', models.CharField(max_length=128)),
                ('DomicilioUsuario', models.CharField(max_length=128)),
                ('FechaEstimadaOrden', models.DateField()),
                ('SKUProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.producto')),
            ],
        ),
    ]
