# Generated by Django 4.2.16 on 2024-10-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='CategoriaProducto',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='EstaOferta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='PrecioOferta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
