# Generated by Django 4.2.16 on 2024-11-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PrecioOferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PrecioProducto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
