# Generated by Django 4.2.16 on 2024-11-23 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenaveterinario',
            name='FechaRespuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resenaveterinario',
            name='RespuestaVeterinario',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta del veterinario'),
        ),
        migrations.AlterField(
            model_name='perfilveterinario',
            name='Descripcion',
            field=models.TextField(blank=True, default='Sin descripción disponible', help_text='Describa su experiencia y servicios principales', null=True, verbose_name='Descripción Profesional'),
        ),
        migrations.AlterField(
            model_name='perfilveterinario',
            name='TelefonoVeterinario',
            field=models.BigIntegerField(blank=True, help_text='Ingrese los 9 dígitos de su número celular', null=True, validators=[django.core.validators.MinValueValidator(900000000, message='El número debe tener 9 dígitos'), django.core.validators.MaxValueValidator(999999999, message='El número debe tener 9 dígitos')], verbose_name='Teléfono'),
        ),
    ]
