# Generated by Django 4.2.16 on 2024-10-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_producto_categoriaproducto_producto_estaoferta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='CategoriaProducto',
            field=models.FloatField(choices=[(0.1, 'Alimentos'), (0.2, 'Accesorios'), (0.3, 'Juguetes'), (0.4, 'Camas y rascadores')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='TipoAnimal',
            field=models.FloatField(choices=[(0.1, 'Gato'), (0.2, 'Perro'), (0.3, 'Ave'), (0.4, 'Hamster')]),
        ),
    ]
