# Generated by Django 4.2.16 on 2024-11-15 21:52

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_alter_producto_preciooferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='FechaEstimadaOrden',
        ),
        migrations.AddField(
            model_name='orden',
            name='EstadoPago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='FechaOrden',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='MontoTotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='TokenWebpay',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='CodigoUnicoOrden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
