# Generated by Django 4.2.16 on 2024-11-26 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_resenaveterinario_fecharespuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadveterinario',
            name='EstadoHorario',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviciopersonalizado',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del servicio', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['Fecha', 'HorarioInicio'], name='tiendita_di_Fecha_3a168b_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['EstaDisponible', 'EstadoHorario'], name='tiendita_di_EstaDis_f684f4_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['Fecha', 'EstaDisponible'], name='tiendita_di_Fecha_2eb0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['veterinario', 'Fecha'], name='tiendita_di_veterin_9415e7_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['EstadoHorario'], name='tiendita_di_EstadoH_472a71_idx'),
        ),
    ]
