# Generated by Django 4.2.16 on 2024-11-16 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0003_remove_orden_fechaestimadaorden_orden_estadopago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='CodigoUnicoOrden',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='DomicilioUsuario',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='EmailUsuario',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='EstadoPago',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='MontoTotal',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='NombreProducto',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='RutUsuario',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='SKUProducto',
        ),
        migrations.AddField(
            model_name='orden',
            name='ApellidoCliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='CostoEnvio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='DireccionCliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='EmailCliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='EstadoOrden',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='NombreCliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='TelefonoCliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='TotalOrden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orden',
            name='TokenWebpay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('PrecioProducto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CantidadProducto', models.IntegerField(blank=True, null=True)),
                ('SKUProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendita.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tiendita.orden')),
            ],
        ),
    ]
