# Generated by Django 4.2.16 on 2024-11-26 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0003_disponibilidadveterinario_estadohorario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento_google_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('evento_google_veterinario', models.CharField(blank=True, max_length=255, null=True)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendita.disponibilidadveterinario')),
                ('servicios', models.ManyToManyField(related_name='citas', to='tiendita.serviciopersonalizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='tiendita.perfilveterinario')),
            ],
            options={
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
