# Generated by Django 4.2.16 on 2024-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0003_alter_producto_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='EstaOferta',
            field=models.BooleanField(default=False),
        ),
    ]
