# Generated by Django 4.2.16 on 2024-10-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0004_alter_producto_estaoferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='EstaOferta',
        ),
    ]
