# Generated by Django 4.2.16 on 2024-11-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0004_rename_codigounicoorden_orden_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('CodigoServicio', models.AutoField(primary_key=True, serialize=False)),
                ('NombreServicio', models.CharField(max_length=100)),
                ('TipoServicio', models.CharField(choices=[('PELUQUERIA', 'Peluquería'), ('LIMPIEZA', 'Limpieza'), ('DENTAL', 'Limpieza Dental'), ('VACUNACION', 'Vacunación')], max_length=20)),
                ('LocalidadServicio', models.CharField(max_length=100)),
                ('HorarioInicioServicio', models.TimeField()),
                ('HorarioCierreServicio', models.TimeField()),
                ('DisponibilidadServicio', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('experiencia_años', models.CharField(max_length=150)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
            },
        ),
        migrations.AlterModelOptions(
            name='veterinaria',
            options={'verbose_name': 'Veterinaria', 'verbose_name_plural': 'Veterinarias'},
        ),
        migrations.RemoveField(
            model_name='veterinaria',
            name='CalificacionVeterinaria',
        ),
        migrations.RemoveField(
            model_name='veterinaria',
            name='TipoAnimal',
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='CodigoVeterinaria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='DisponibilidadVeterinaria',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='HorarioCierreVeterinaria',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='HorarioInicioVeterinaria',
            field=models.TimeField(),
        ),
        migrations.AddIndex(
            model_name='veterinaria',
            index=models.Index(fields=['LocalidadVeterinaria'], name='tiendita_ve_Localid_f10f52_idx'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.veterinaria'),
        ),
        migrations.AddField(
            model_name='citaveterinaria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citaveterinaria',
            name='veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.veterinaria'),
        ),
        migrations.AddField(
            model_name='citaveterinaria',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.veterinario'),
        ),
        migrations.AddIndex(
            model_name='veterinario',
            index=models.Index(fields=['especialidad'], name='tiendita_ve_especia_53528d_idx'),
        ),
    ]
