# Generated by Django 4.2.16 on 2024-10-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0005_remove_producto_estaoferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='EstaOferta',
            field=models.BooleanField(default=False),
        ),
    ]
