# Generated by Django 4.2.16 on 2024-11-18 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0005_citaveterinaria_servicio_veterinario_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='veterinario',
            name='tiendita_ve_especia_53528d_idx',
        ),
        migrations.AddField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='nombre_veterinario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='veterinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendita.veterinaria'),
        ),
    ]
