# Generated by Django 4.2.16 on 2024-11-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0006_remove_veterinario_tiendita_ve_especia_53528d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ImagenPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
