# Generated by Django 4.2.16 on 2024-11-10 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiendita', '0006_producto_estaoferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RutUsuario', models.IntegerField(unique=True)),
                ('NombreUsuario', models.CharField(max_length=80)),
                ('PasswordUsuario', models.CharField(max_length=20)),
                ('EmailUsuario', models.CharField(max_length=128)),
                ('DomicilioUsuario', models.CharField(max_length=128)),
                ('TipoAnimal', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='RutUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.usuarioprofile'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
