# Generated by Django 4.2.16 on 2024-11-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0007_customuser_imagenperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ApellidoUsuario',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='TelefonoUsuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='TipoAnimal',
            field=models.FloatField(blank=True, choices=[(0.1, 'Gato'), (0.2, 'Perro'), (0.3, 'Ave'), (0.4, 'Hamster')], null=True),
        ),
    ]
