# Generated by Django 4.2.16 on 2024-11-19 04:10

from django.db import migrations, models
import tiendita.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0008_customuser_apellidousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ImagenPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[tiendita.models.validate_image_file_extension]),
        ),
    ]
